version: 2
jobs:
  build:
    working_directory: ~/wp-e2e-tests
    docker:
      - image: 'circleci/node:8.11.0-browsers'
        environment:
          NODE_ENV: test
          TARGET: CANARY
    steps:
      - checkout
      - run: git submodule init
      - run: git submodule update --remote --force
      - run: cd wp-e2e-tests && git checkout origin/${E2E_BRANCH-master}
      - restore_cache:
          key: v1-{{ checksum "wp-e2e-tests/package-lock.json" }}
      - run: cd wp-e2e-tests && npm install
      - save_cache:
          key: v1-{{ checksum "wp-e2e-tests/package-lock.json" }}
          paths:
            - "wp-e2e-tests/node_modules"
      - run: cd wp-e2e-tests && npm run decryptconfig && ./run.sh -R -C $RUN_ARGS
      - store_test_results:
          path: wp-e2e-tests/reports/
      - store_artifacts:
          path: wp-e2e-tests/reports/
      - store_artifacts:
          path: wp-e2e-tests/screenshots/
