version: 2
jobs:
  build:
    working_directory: ~/wp-calypso
    docker:
      - image: 'circleci/node:$NODE_VERSION-browsers'
        environment:
          NODE_ENV: test
          TARGET: CANARY
    steps:
      - checkout
      - run: git submodule init
      - run: git submodule update --remote --force
      - run: cd wp-calypso && git checkout ${stage_revision-origin/master}
      - restore_cache:
          keys:
             - v1-{{ checksum "wp-calypso/.nvmrc" }}-{{ checksum "wp-calypso/test/e2e/package-lock.json" }}
             - v1-{{ checksum "wp-calypso/.nvmrc" }}
      - run: |
          cd wp-calypso/test/e2e &&
          CHROMEDRIVER_VERSION=$(<.chromedriver_version) npm ci
      - save_cache:
          key: v1-{{ checksum "wp-calypso/.nvmrc" }}-{{ checksum "wp-calypso/test/e2e/package-lock.json" }}
          paths:
            - ~/.npm
      - run: sudo chmod +x wp-calypso/test/e2e/node_modules/.bin/magellan
      - run: cd wp-calypso/test/e2e && npm run decryptconfig && ./run.sh -R -C $RUN_ARGS
      - store_test_results:
          path: wp-calypso/test/e2e/reports/
      - store_artifacts:
          path: wp-calypso/test/e2e/reports/
      - store_artifacts:
          path: wp-calypso/test/e2e/screenshots/
