version: 2
jobs:
  build:
    working_directory: ~/wp-calypso
    docker:
      - image: "circleci/node:$NODE_VERSION-browsers"
        environment:
          NODE_ENV: test
          TARGET: CANARY
          DETECT_CHROMEDRIVER_VERSION: "false"
          CHROMEDRIVER_FILEPATH: /usr/local/bin/chromedriver
    steps:
      - checkout
      - run: git submodule init
      - run: git submodule update --remote --force
      - run: cd wp-calypso && git checkout ${stage_revision-origin/trunk}
      - restore_cache:
          keys:
            - v1-packages-{{ checksum "wp-calypso/.nvmrc" }}-{{ checksum "wp-calypso/yarn.lock" }}-{{ checksum "wp-calypso/test/e2e/package.json" }}
            - v1-packages-{{ checksum "wp-calypso/.nvmrc" }}-{{ checksum "wp-calypso/yarn.lock" }}
            - v1-packages-{{ checksum "wp-calypso/.nvmrc" }}
            - v1-packages
      - run: |
          cd wp-calypso/test/e2e && yarn --frozen-lockfile
      - save_cache:
          key: v1-packages-{{ checksum "wp-calypso/.nvmrc" }}-{{ checksum "wp-calypso/yarn.lock" }}-{{ checksum "wp-calypso/test/e2e/package.json" }}
          paths:
            - ~/.cache/yarn
      - run: |
          google-chrome --version > wp-calypso/test/e2e/.chromedriver_version
          echo -n "Google Chrome version: " && cat wp-calypso/test/e2e/.chromedriver_version
      - run: sudo chmod +x wp-calypso/test/e2e/node_modules/.bin/magellan
      - run: cd wp-calypso/test/e2e && yarn run decryptconfig && ./run.sh -R -C $SAUCE_ARG $RUN_ARGS
      - store_test_results:
          path: wp-calypso/test/e2e/reports/
      - store_artifacts:
          path: wp-calypso/test/e2e/reports/
      - store_artifacts:
          path: wp-calypso/test/e2e/screenshots/
