version: 2
jobs:
  build:
    working_directory: ~/wp-e2e-tests
    docker:
      - image: 'circleci/node:10.4.1-browsers'
        environment:
          NODE_ENV: test
          TARGET: CANARY
    steps:
      - checkout
      - run: git submodule init
      - run: git submodule update --remote --force
      - run: cd wp-e2e-tests && git checkout origin/${E2E_BRANCH-master}
      - restore_cache:
          keys: 
             - v1-node10-{{ checksum "wp-e2e-tests/package-lock.json" }}
             - v1-node10
             
      - run: cd wp-e2e-tests && npm ci
      - save_cache:
          key: v1-node10-{{ checksum "wp-e2e-tests/package-lock.json" }}
          paths:
            - ~/.npm
      - run: sudo chmod +x wp-e2e-tests/node_modules/.bin/magellan
      - run: cd wp-e2e-tests && npm run decryptconfig && ./run.sh -R -C $RUN_ARGS
      - store_test_results:
          path: wp-e2e-tests/reports/
      - store_artifacts:
          path: wp-e2e-tests/reports/
      - store_artifacts:
          path: wp-e2e-tests/screenshots/
